version: '3.7'



services:

	server:
		build:
      		  context: .
      		  dockerfile: server/Dockerfile
    		restart: always
    		cap_add:
      		  - NET_ADMIN
    		networks:
      			network:
        		  ipv4_address: 172.20.1.0
    		expose:
      		  - "1-65535"
	
	client_1:
	
	client_2:
	
	client_3:
	
	client_4:

networks:
  network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
